name: ampher-prod web app

on:
  push:
    branches:
      - production  # Trigger deployment when changes are pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Add permission to write the id-token

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: spn  # Specify Service Principal authentication type

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}
          registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/vite-react-app:v1 .
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/vite-react-app:v1

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ampher-prod
          slot-name: production
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/vite-react-app:v1
